CREATE TABLE REFROG.SSO_TOKEN(
ID VARCHAR(50) NOT NULL PRIMARY KEY DEFAULT gen_random_uuid(),
KIND VARCHAR(10) NOT NULL,
PARAMS VARCHAR(500) NOT NULL,
USE_STATUS VARCHAR(1) NOT NULL DEFAULT 'N',
CREATE_TIME TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON COLUMN REFROG.SSO_TOKEN.PARAMS IS 'String or json';